apiVersion: skaffold/v2beta7
kind: Config
metadata:
  name: omar-stager-core
build:
  artifacts:
    - image: registry.iap.maxar.com/gegd/omar/omar-stager-core
      jib: 
        project: omar-stager-core-app
      context: ./apps/omar-stager-core-app
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: omar-stager-core # this is the helm release name                
        chartPath: ./apps/omar-stager-core-app/chart
        valuesFiles:
          - ./apps/omar-stager-core-app/values-dev.yaml # provides values to override defaults in chart
        namespace: omar-3pa-dev
        setValueTemplates:
          image.tag: latest
          image.name: omar-stager-core
